name = "map"
main = "worker/index.js"
compatibility_date = "2026-06-27"

[[rules]]
type = "Text"
globs = ["**/*.md"]
fallthrough = true

[vars]
MAP_AI_PROVIDER = "cloudflare"
CF_MODEL = "@cf/meta/llama-3.1-8b-instruct"
HF_MODEL = "Qwen/Qwen3-4B-Instruct-2507:nscale"
HF_ENDPOINT = "https://router.huggingface.co/v1/chat/completions"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "MAP_DB"

[[routes]]
pattern = "map.indexmod.press"
custom_domain = true
